title = "Seller Account Management Services: Grow Your E-Commerce Business"
enableRobotsTXT = true
baseURL = "https://c2l.asia/"

[params]
  name = "C2L"
  logo = "/images/c2l_icon.webp"
  description = "A provider of seller account management services. We help e-commerce sellers succeed on multiple platforms, including Amazon, Noon etc."

[menu]
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 20

  [[menu.main]]
    identifier = "others"
    name = "Others"
    url = "/others"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 30
