title = "C2L - Come to life"
enableRobotsTXT = true
baseURL = "https://c2l.asia/"

[params]
  name = "C2L"
  logo = "/images/c2l_icon.webp"
  description = "We are eCommerce management service provider so you can focus on important things which is your product."

[menu]
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 20

  [[menu.main]]
    identifier = "others"
    name = "Others"
    url = "/others"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 30
