title = "C2L - Come to life"
[params]
  name = "C2L"
  logo = "/images/c2l_icon.webp"

[menu]
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 20

  [[menu.main]]
    identifier = "others"
    name = "Others"
    url = "/others"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 30
